/**
 * assets.js — Asset definitions for your LittleJS game.
 *
 * Each entry is a keyed descriptor.  Two types are supported:
 *
 *   TEXTURES
 *   ─────────
 *   source: 'file'        → loaded from `path` via ImageCache before game starts.
 *   source: 'procedural'  → generated at runtime; add your own draw code in the
 *                           relevant scene or utils file.
 *   source: 'disabled'    → ignored entirely (useful to stub an entry).
 *
 *   AUDIO
 *   ─────
 *   source: 'procedural'  → generated by ZzFX (a LittleJS built-in); params is
 *                           a ZzFX parameter array.
 *   source: 'file'        → loaded from `path` (mp3 / ogg / wav).
 *   source: 'disabled'    → silently skipped.
 *
 *   The `volume` field (0-1) on audio entries is a per-sound multiplier that
 *   is combined with the master / sfx volume from config.js.
 *
 * HOW TO CUSTOMISE
 * ────────────────
 * 1. Add your own texture keys (match BLOCK_IMAGE_KEYS or reference them
 *    directly with assetManager.getImage('myKey')).
 * 2. Add your own audio keys, then call game.audioSystem._play('myKey') in
 *    your scene, or wrap it in a named method on AudioSystem.
 * 3. Set source:'disabled' instead of deleting entries you don't need yet —
 *    the AssetManager simply skips them.
 */

export const ASSETS = {

    // ── TEXTURES ─────────────────────────────────────────────────────────────

    // Example file-based textures.  Replace / remove as needed.
    //
    // backgroundDesktop: {
    //     type:   'texture',
    //     source: 'file',
    //     path:   'images/background-desktop.png',
    // },
    //
    // backgroundMobile: {
    //     type:   'texture',
    //     source: 'file',
    //     path:   'images/background-mobile.png',
    // },
    //
    // logo: {
    //     type:   'texture',
    //     source: 'file',
    //     path:   'images/logo.png',
    // },

    bgClouds: {
        type: 'texture',
        source: 'procedural', // Can be changed to 'file' and path provided
        // path:   'images/bgClouds.png',
    },

    debris: {
        type: 'texture',
        source: 'procedural',
        // path: 'images/debris.png',
    },

    bomb: {
        type: 'texture',
        source: 'procedural',
        // path: 'images/bomb.png',
    },

    // ── AUDIO ─────────────────────────────────────────────────────────────────

    // UI click — ZzFX procedural (works without any audio files)
    uiClick: {
        type: 'audio',
        source: 'procedural',
        volume: 0.6,
        // ZzFX params: [volume, randomness, freq, attack, sustain, release, shape, ...]
        params: [0.5, 0, 300, 0.01, 0.02, 0.05, 0, 1],
    },

    // Generic positive / confirmation sound
    confirm: {
        type: 'audio',
        source: 'procedural',
        volume: 1.0,
        params: [1, 0, 523, 0.01, 0.1, 0.2, 0, 1.5, 0, 0, 0, 0, 0, 1],
    },

    // Generic negative / error sound
    deny: {
        type: 'audio',
        source: 'procedural',
        volume: 0.8,
        params: [1, 0, 220, 0.05, 0.1, 0.2, 1, 1, 0, 0, 0, 0, 0, 1],
    },

    // Background music — set source:'file' + path to enable.
    music: {
        type: 'audio',
        source: 'disabled',   // change to 'file' and add path + loop below
        volume: 0.3,
        // path: 'audio/music.mp3',
        // loop: true,
    },
};
